name:First work flow
on: workflow_dispatch
jobs:
  firts-job:
    runs-on:
      steps:  
      - name: hello github action  
        run : echo "hello rizwan"
      - name: By github action
        run : echo "By rizwan"
