name: First work flow
on: workflow_dispatch
jobs:
  firts-job:
    runs-on: ubuntu-latest
    steps:
       - name: Hello Git action
         run: echo "hello test"
       - name: by git action
         run: echo "by"
    
     
